# Site settings
title: Erka travels
description: > # this means to ignore newlines until "baseurl:"
  Блог о моих путешествия или всём, что связано с ними.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://erka.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

ga_id: UA-1763671-2
# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
