baseURL = 'https://erka.github.io/'
languageCode = 'en-us'
title = 'Dark Light'
theme = 'fowery'
ignoreFiles = ['/static/.*\.md', '/tools/', '/scripts/']

[author]
name = 'Roman Dmytrenko'

[params]
description = 'Exploring the art of storytelling, one foot at a time.'
keywords = ['life', 'software', 'engineering', 'travel']
favicon = 'favicon'
dateShortFormat = 'Jan 02'


[permalinks]
posts = "/blog/:slug"

[markup.highlight]
style = "catppuccin-frappe"

[markup.goldmark.parser.attribute]
block = true
